// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgwZKG93XVmjSwBvUfbIB96FE5gtbO_V8',
    appId: '1:1051556054267:web:4e5cac6895e51d4b779c5e',
    messagingSenderId: '1051556054267',
    projectId: 'iet-office-tsy-e1e18',
    authDomain: 'iet-office-tsy-e1e18.firebaseapp.com',
    databaseURL: 'https://iet-office-tsy-e1e18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iet-office-tsy-e1e18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA18kJXrxExgWSlwiHvwzTigRgv9MfrKoQ',
    appId: '1:1051556054267:android:c506445cf849928b779c5e',
    messagingSenderId: '1051556054267',
    projectId: 'iet-office-tsy-e1e18',
    databaseURL: 'https://iet-office-tsy-e1e18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iet-office-tsy-e1e18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXHGShw0CvAvIZiH2XjCM_MOPhw50SNgY',
    appId: '1:1051556054267:ios:d8916141d878d95d779c5e',
    messagingSenderId: '1051556054267',
    projectId: 'iet-office-tsy-e1e18',
    databaseURL: 'https://iet-office-tsy-e1e18-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iet-office-tsy-e1e18.firebasestorage.app',
    iosClientId: '1051556054267-lo1f0hpmq1jgei8iadsh7kn6e6vq3iq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.astravalSmart',
  );
}
